import type { Player, Match, FormResult } from "./types"

function parseForm(s: string): FormResult[] {
  if (!s) return []
  return s.split("").map((c) => c as FormResult)
}

// Data from MNF League Table 2025 + Top Scorer table
// The -points column (after Captain) represents minus points deductions
// Points = (W*3) + (D*1) - minusPoints
export const initialPlayers: Player[] = [
  { id: "p1",  name: "Zulbab",   password: "zulbab",  played: 18, won: 10, drawn: 1, lost: 7, captainCount: 3, minusPoints: 0,  goalDifference: 31,  points: 31, goals: 39, form: parseForm("LWWWWWWWWWWLWDLL"), previousPosition: 1,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p2",  name: "Ali S",    password: "ali s",   played: 16, won: 10, drawn: 1, lost: 5, captainCount: 2, minusPoints: 4,  goalDifference: 13,  points: 27, goals: 21, form: parseForm("WWWLWLWWDLWW"),     previousPosition: 4,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p3",  name: "Naqi",     password: "naqi",    played: 16, won: 9,  drawn: 1, lost: 6, captainCount: 2, minusPoints: 1,  goalDifference: 6,   points: 27, goals: 28, form: parseForm("WWWWLLDWWLLWDLW"),  previousPosition: 2,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p4",  name: "Assad K",  password: "assad k", played: 11, won: 8,  drawn: 1, lost: 2, captainCount: 0, minusPoints: 0,  goalDifference: 17,  points: 25, goals: 14, form: parseForm("WWWWWWLDWWW"),      previousPosition: 1,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p5",  name: "Diggy",    password: "diggy",   played: 15, won: 8,  drawn: 1, lost: 6, captainCount: 3, minusPoints: 0,  goalDifference: 3,   points: 25, goals: 6,  form: parseForm("WWWWLWLLWWD"),      previousPosition: 2,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p6",  name: "Shehan",   password: "shehan",  played: 9,  won: 7,  drawn: 0, lost: 2, captainCount: 0, minusPoints: 0,  goalDifference: 17,  points: 21, goals: 0,  form: parseForm("WWWDWWWL"),          previousPosition: 6,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p7",  name: "Haider",   password: "haider",  played: 16, won: 7,  drawn: 0, lost: 9, captainCount: 2, minusPoints: 1,  goalDifference: 1,   points: 20, goals: 0,  form: parseForm("LWLWWWLLWWWLWLL"),  previousPosition: 7,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p8",  name: "Zeze",     password: "zeze",    played: 15, won: 6,  drawn: 1, lost: 8, captainCount: 6, minusPoints: 0,  goalDifference: 0,   points: 18, goals: 4,  form: parseForm("LWLWWLLWWWLDLL"),   previousPosition: 8,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p9",  name: "Hassan",   password: "hassan",  played: 15, won: 6,  drawn: 0, lost: 9, captainCount: 3, minusPoints: 1,  goalDifference: 1,   points: 17, goals: 3,  form: parseForm("LWLLWLLLWWLL"),     previousPosition: 9,  registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p10", name: "Zain S",   password: "zain s",  played: 14, won: 7,  drawn: 1, lost: 6, captainCount: 0, minusPoints: 6,  goalDifference: 9,   points: 16, goals: 5,  form: parseForm("WWWWWWWLWDWLL"),    previousPosition: 10, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p11", name: "Soliman",  password: "soliman", played: 7,  won: 5,  drawn: 0, lost: 2, captainCount: 1, minusPoints: 3,  goalDifference: 7,   points: 12, goals: 0,  form: parseForm("WLWWWDW"),           previousPosition: 12, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p12", name: "Zareem",   password: "zareem",  played: 11, won: 4,  drawn: 0, lost: 7, captainCount: 1, minusPoints: 1,  goalDifference: 1,   points: 11, goals: 4,  form: parseForm("LWLLWWWLLLW"),      previousPosition: 14, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p13", name: "Oz",       password: "oz",      played: 6,  won: 4,  drawn: 0, lost: 2, captainCount: 0, minusPoints: 2,  goalDifference: 2,   points: 10, goals: 3,  form: parseForm("WWLLWW"),             previousPosition: 16, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p14", name: "Aman",     password: "aman",    played: 9,  won: 3,  drawn: 1, lost: 5, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 10, goals: 5,  form: parseForm("LWLLLLDLW"),         previousPosition: 11, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p15", name: "Jaffar",   password: "jaffar",  played: 9,  won: 3,  drawn: 1, lost: 5, captainCount: 0, minusPoints: 1,  goalDifference: 1,   points: 9,  goals: 0,  form: parseForm("LLLLWLLDWW"),        previousPosition: 18, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p16", name: "Fazal",    password: "fazal",   played: 12, won: 3,  drawn: 0, lost: 9, captainCount: 2, minusPoints: 0,  goalDifference: -28, points: 9,  goals: 1,  form: parseForm("LLWLLWLLLW"),         previousPosition: 19, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p17", name: "Waasil",   password: "waasil",  played: 6,  won: 3,  drawn: 0, lost: 3, captainCount: 0, minusPoints: 1,  goalDifference: 3,   points: 8,  goals: 3,  form: parseForm("WLLWW"),              previousPosition: 13, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p18", name: "Mehdi",    password: "mehdi",   played: 4,  won: 3,  drawn: 0, lost: 1, captainCount: 1, minusPoints: 2,  goalDifference: 14,  points: 7,  goals: 1,  form: parseForm("WWWW"),               previousPosition: 15, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p19", name: "Adeel",    password: "adeel",   played: 3,  won: 2,  drawn: 0, lost: 1, captainCount: 1, minusPoints: 0,  goalDifference: 2,   points: 6,  goals: 3,  form: parseForm("WWL"),                previousPosition: 17, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p20", name: "Vineet",   password: "vineet",  played: 7,  won: 2,  drawn: 1, lost: 4, captainCount: 1, minusPoints: 3,  goalDifference: 1,   points: 4,  goals: 0,  form: parseForm("LWWWLDLL"),           previousPosition: 20, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p21", name: "Hussain",  password: "hussain", played: 1,  won: 1,  drawn: 0, lost: 0, captainCount: 0, minusPoints: 0,  goalDifference: 7,   points: 3,  goals: 1,  form: parseForm("W"),                  previousPosition: 21, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p22", name: "Zain R",   password: "zain r",  played: 1,  won: 1,  drawn: 0, lost: 0, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 3,  goals: 1,  form: parseForm("W"),                  previousPosition: 22, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p23", name: "Nina",     password: "nina",    played: 2,  won: 1,  drawn: 0, lost: 1, captainCount: 0, minusPoints: 0,  goalDifference: 3,   points: 3,  goals: 1,  form: parseForm("WL"),                 previousPosition: 23, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p24", name: "Paan",     password: "paan",    played: 1,  won: 1,  drawn: 0, lost: 0, captainCount: 0, minusPoints: 0,  goalDifference: 3,   points: 3,  goals: 1,  form: parseForm("W"),                  previousPosition: 24, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p25", name: "Matthew",  password: "matthew", played: 1,  won: 1,  drawn: 0, lost: 0, captainCount: 0, minusPoints: 0,  goalDifference: 2,   points: 3,  goals: 2,  form: parseForm("W"),                  previousPosition: 25, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p26", name: "Zain C",   password: "zain c",  played: 2,  won: 1,  drawn: 0, lost: 1, captainCount: 0, minusPoints: 0,  goalDifference: 1,   points: 3,  goals: 0,  form: parseForm(""),                   previousPosition: 26, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p27", name: "Mazhar",   password: "mazhar",  played: 11, won: 1,  drawn: 1, lost: 9, captainCount: 0, minusPoints: 0,  goalDifference: -22, points: 3,  goals: 13, form: parseForm("LLLLLWLDLL"),         previousPosition: 27, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p28", name: "Akbar",    password: "akbar",   played: 2,  won: 1,  drawn: 0, lost: 1, captainCount: 0, minusPoints: 1,  goalDifference: 0,   points: 2,  goals: 1,  form: parseForm("WDL"),                previousPosition: 28, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p29", name: "AJ",       password: "aj",      played: 3,  won: 1,  drawn: 0, lost: 2, captainCount: 0, minusPoints: 0,  goalDifference: -2,  points: 2,  goals: 0,  form: parseForm("WLL"),                previousPosition: 29, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p30", name: "Zaki",     password: "zaki",    played: 4,  won: 0,  drawn: 1, lost: 3, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 1,  goals: 5,  form: parseForm("WLLD"),               previousPosition: 30, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p31", name: "Mo Kash",  password: "mo kash", played: 1,  won: 0,  drawn: 0, lost: 1, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 0,  goals: 0,  form: parseForm(""),                   previousPosition: 31, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  { id: "p32", name: "Patch",    password: "patch",   played: 1,  won: 0,  drawn: 0, lost: 1, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 0,  goals: 0,  form: parseForm("L"),                  previousPosition: 32, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
  // Abbas is in top scorer table but not league table - adding with goals only
  { id: "p33", name: "Abbas",    password: "abbas",   played: 1,  won: 0,  drawn: 0, lost: 0, captainCount: 0, minusPoints: 0,  goalDifference: 0,   points: 0,  goals: 2,  form: [],                             previousPosition: 33, registrationStatus: "out", registeredAt: null, paid: false, isWinningTeam: false },
]

export const initialMatches: Match[] = []
